[config]
schemaVersion = "0.0.1"

[package]
namespace = "deca"
name = "CommunityCommands"
versionNumber = "0.1.0"
description = "Commands for the community, by the community."
websiteUrl = "https://github.com/decaprime/CommunityCommands"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.1"
deca-VampireCommandFramework = "0.5.2"

[build]
icon = "./logo.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://v-rising.thunderstore.io"
communities = ["v-rising"]
categories = ["gloomrot-update", "mods", "server"]
